server:
  port: 3000

spring:
  application:
    name: gateway

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 20000
  ConnectTimeout: 20000


eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://registry.unibz.com:8761/eureka/
    instance:
      hostname: localhost

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  routes:
    authentication:
      path: /authentication/**
      serviceId: authentication
      stripPrefix: true
      sensitiveHeaders:
    account:
      path: /account/**
      serviceId: account
      stripPrefix: true
      sensitiveHeaders:
    mail:
      path: /mail/**
      stripPrefix: true
      serviceId: mail
      url: http://mail.unibz.com:8001
      sensitiveHeaders:

#authentication:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.WeightedReponseTimeRule

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000


authentication:
  uri: http://authentication.unibz.com:5001/validate