version: '2'

services:

  mysql-account:
    image: mysql:latest
    hostname: mysql-account.unibz.com
    environment:
      MYSQL_ROOT_PASSWORD: root
    expose:
      - 3306
    ports:
      - 3306:3306
    networks:
      imsnetwork:
        aliases:
          - mysql-account.unibz.com

  mongo-auth:
    image: mongo-service:latest
    environment:
      MONGODB_PASSWORD: mypassword
    expose:
      - 27017
#    volumes:
#        - /data/db:/data/db
    restart: always
    networks:
      imsnetwork:
        aliases:
          - mongodb-auth.unibz.com

  registry:
    image: registry-service:latest
    hostname: registry.unibz.com
    ports:
      - 8761:8761
    networks:
      imsnetwork:
        aliases:
          - registry.unibz.com

  gateway:
    image: gateway-service:latest
    hostname: gateway.unibz.com
    ports:
      - "3000:3000"
    expose:
      - 3000
    networks:
      imsnetwork:
        aliases:
          - gateway.unibz.com

  authentication:
    image: authentication-service:latest
    hostname: authentication.unibz.com
    depends_on:
      - registry
      - mongo-auth
    ports:
      - 5001:5001
    networks:
      imsnetwork:
        aliases:
          - authentication.unibz.com

  account:
    image: account-service:latest
    environment:
      ACCOUNT_SERVICE_PASSWORD: accountpassword
    hostname: account.unibz.com
    depends_on:
      - mysql-account
      - registry
    ports:
      - 6000:6000
    volumes:
      - ~/images:/images
    networks:
      imsnetwork:
        aliases:
          - account.unibz.com

  excursion:
    image: excursion-service:latest
#    environment:
#      ACCOUNT_SERVICE_PASSWORD: accountpassword
    hostname: excursion.unibz.com
    depends_on:
      - mysql-account
      - registry
    ports:
      - 9001:9001
    volumes:
      - ~/images:/images
    networks:
      imsnetwork:
        aliases:
          - excursion.unibz.com

  mail:
    image: mail-service:latest
    hostname: mail.unibz.com
    depends_on:
      - mongo-auth
    ports:
      - 8001:8001
    networks:
      imsnetwork:
        aliases:
          - mail.unibz.com

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: rabbituser
      RABBITMQ_DEFAULT_PASS: rabbitpass
    ports:
      - 5672:5672
      - 15672:15672
      - 8080:8080
    networks:
      imsnetwork:
        aliases:
          - rabbitmq.unibz.com

# NETWORK SETTINGS
networks:
  imsnetwork:
    driver: bridge

